title: Bolaji Ayodeji
email: mailtobolaji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I build and deploy softwares with great focus on stunning user interface, design, optimization and security.
baseurl: '/startjekyll' # the subpath of your site, e.g. /blog
url: 'http://bolajiayodeji.github.io/startjekyll'
twitter_username: iambolajiayo
github_username: bolajiayodeji

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
